Insert INTO [DepRequests] ([reqId],[reqDep]) Values (5,4)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (5,5)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (5,6)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (5,7)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (4,3)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (4,5)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (4,6)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (4,7)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (3,3)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (3,4)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (3,5)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (3,6)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (3,7)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (7,8)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (7,9)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (2,3)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (2,5)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (2,6)
Insert INTO [DepRequests] ([reqId],[reqDep]) Values (2,7)


select * from [DepRequests]