Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (5,3,4)
Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (5,3,5)
Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (5,3,6)
Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (4,6,3)
Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (4,6,4)
Insert INTO [DepRequests] ([reqId],[cDep],[reqDep]) Values (4,6,5)